#!/usr/bin/env python3
"""Build and render the skill dependency graph.

Relationship semantics (see docs/SKILL-SPEC.md):
  requires   - hard prerequisite; directed edge; must be acyclic
  related    - soft sibling pointer; undirected in spirit (we render both
               directions but do NOT require reciprocity, since it's common
               for a broad skill to link to many narrow siblings that don't
               link back)
  conflicts  - two skills that give contradictory guidance for the same
               situation; symmetric; currently expected to be empty across
               the repo (no known contradictions) but the field exists so a
               future audit finding has somewhere to go instead of prose.

Usage:
    python scripts/build_dependency_graph.py            # print summary
    python scripts/build_dependency_graph.py --write     # (re)write docs/SKILL-GRAPH.md
    python scripts/build_dependency_graph.py --check     # exit 1 if docs/SKILL-GRAPH.md is stale
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import skills_lib as sl  # noqa: E402

GRAPH_DOC = sl.REPO_ROOT / "docs" / "SKILL-GRAPH.md"


def find_cycles(skills: list[sl.Skill]) -> list[list[str]]:
    """DFS cycle detection over the directed `requires` graph. Returns one
    representative cycle path per strongly-connected offending node found."""
    graph = {s.slug: (s.frontmatter.get("requires") or []) for s in skills}
    valid_slugs = set(graph)
    graph = {k: [t for t in v if t in valid_slugs] for k, v in graph.items()}

    WHITE, GRAY, BLACK = 0, 1, 2
    color = {s: WHITE for s in graph}
    cycles: list[list[str]] = []

    def dfs(node: str, stack: list[str]) -> None:
        color[node] = GRAY
        stack.append(node)
        for neighbor in graph.get(node, []):
            if color.get(neighbor) == GRAY:
                idx = stack.index(neighbor)
                cycles.append(stack[idx:] + [neighbor])
            elif color.get(neighbor, WHITE) == WHITE:
                dfs(neighbor, stack)
        stack.pop()
        color[node] = BLACK

    for node in graph:
        if color[node] == WHITE:
            dfs(node, [])
    return cycles


def find_orphans(skills: list[sl.Skill]) -> list[str]:
    """Skills with no incoming or outgoing `related`/`requires` edges at all."""
    referenced: set[str] = set()
    for s in skills:
        referenced.update(s.frontmatter.get("related") or [])
        referenced.update(s.frontmatter.get("requires") or [])
    orphans = []
    for s in skills:
        outgoing = (s.frontmatter.get("related") or []) + (s.frontmatter.get("requires") or [])
        if not outgoing and s.slug not in referenced:
            orphans.append(s.slug)
    return orphans


def render_markdown(skills: list[sl.Skill]) -> str:
    by_slug = sl.by_slug(skills)
    lines = [
        "# Skill Dependency Graph",
        "",
        "**Generated by `scripts/build_dependency_graph.py --write`. Do not hand-edit —",
        "your changes will be overwritten on the next run. Edit the `requires` /",
        "`related` / `conflicts` frontmatter fields in the source SKILL.md files instead.**",
        "",
        "## Mermaid graph (hard `requires` edges only)",
        "",
        "```mermaid",
        "graph LR",
    ]
    any_requires = False
    for s in skills:
        for target in s.frontmatter.get("requires") or []:
            if target in by_slug:
                lines.append(f"  {s.slug} --> {target}")
                any_requires = True
    if not any_requires:
        lines.append("  %% no hard `requires` edges currently declared")
    lines += ["```", "", "## Per-skill relationships", ""]

    for s in sorted(skills, key=lambda x: x.slug):
        req = s.frontmatter.get("requires") or []
        rel = s.frontmatter.get("related") or []
        conf = s.frontmatter.get("conflicts") or []
        lines.append(f"### `{s.slug}` ({s.frontmatter.get('type')}, {s.frontmatter.get('domain')})")
        lines.append(f"- requires: {', '.join(f'`{r}`' for r in req) if req else '_none_'}")
        lines.append(f"- related: {', '.join(f'`{r}`' for r in rel) if rel else '_none_'}")
        lines.append(f"- conflicts: {', '.join(f'`{r}`' for r in conf) if conf else '_none_'}")
        lines.append("")

    cycles = find_cycles(skills)
    orphans = find_orphans(skills)
    lines.append("## Integrity checks")
    lines.append("")
    lines.append(f"- Dependency cycles found: {len(cycles)}")
    for c in cycles:
        lines.append(f"  - {' -> '.join(c)}")
    lines.append(f"- Orphaned skills (no related/requires edges in or out): {len(orphans)}")
    for o in orphans:
        lines.append(f"  - `{o}`")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    skills = sl.load_all_skills()
    rendered = render_markdown(skills)

    if args.write:
        GRAPH_DOC.parent.mkdir(exist_ok=True)
        GRAPH_DOC.write_text(rendered, encoding="utf-8")
        print(f"wrote {GRAPH_DOC}")
        return 0

    if args.check:
        current = GRAPH_DOC.read_text(encoding="utf-8") if GRAPH_DOC.exists() else ""
        if current.strip() != rendered.strip():
            print("docs/SKILL-GRAPH.md is stale — run `python scripts/build_dependency_graph.py --write`")
            return 1
        print("docs/SKILL-GRAPH.md is up to date")
        return 0

    cycles = find_cycles(skills)
    orphans = find_orphans(skills)
    print(f"{len(skills)} skills, {len(cycles)} cycle(s), {len(orphans)} orphan(s)")
    return 1 if cycles else 0


if __name__ == "__main__":
    sys.exit(main())
