#!/usr/bin/env python3
"""Keep README.md's PROJECT-STATS block honest, the same way generate_index.py
keeps INDEX.md honest: compute every number from the actual repo state, never
hand-maintain a count that can silently drift out of date.

Usage:
    python scripts/generate_readme_stats.py --check   # exit 1 if README.md is stale (CI)
    python scripts/generate_readme_stats.py --write    # regenerate the block in place
"""
from __future__ import annotations

import argparse
import sys
import unittest
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import skills_lib as sl  # noqa: E402

README = sl.REPO_ROOT / "README.md"
START = "<!-- PROJECT-STATS:START -->"
END = "<!-- PROJECT-STATS:END -->"

DOMAIN_LABEL = {
    "foundations": "Foundations",
    "classical-ml": "Classical ML",
    "deep-learning": "Deep Learning",
    "llm": "LLM",
    "specialized": "Specialized",
    "mlops": "MLOps",
    "responsible-ai": "Responsible AI",
    "security": "Security",
}
DOMAIN_ORDER = list(DOMAIN_LABEL)


def count_tests() -> int:
    suite = unittest.defaultTestLoader.discover(str(sl.REPO_ROOT / "tests"), pattern="test_*.py")

    def _count(s) -> int:
        total = 0
        for item in s:
            if isinstance(item, unittest.TestSuite):
                total += _count(item)
            else:
                total += 1
        return total

    return _count(suite)


def count_evals() -> tuple[int, int]:
    """Returns (case_file_count, distinct_skills_covered)."""
    evals_dir = sl.REPO_ROOT / "evals"
    files = list(evals_dir.glob("*/*.yaml"))
    covered = {f.parent.name for f in files}
    return len(files), len(covered)


def fmt_counter(counter: Counter, order: list[str] | None = None) -> str:
    keys = order if order else sorted(counter)
    return " · ".join(f"{k} ({counter.get(k, 0)})" for k in keys if counter.get(k, 0))


def render() -> str:
    skills = sl.load_all_skills()
    total = len(skills)
    type_counts = Counter(s.frontmatter.get("type") for s in skills)
    domain_counts = Counter(s.frontmatter.get("domain") for s in skills)
    level_counts = Counter(s.frontmatter.get("level") for s in skills)
    risk_counts = Counter(s.frontmatter.get("risk_level") for s in skills)
    evidence_counts = Counter(s.frontmatter.get("evidence_level") for s in skills)

    eval_files, eval_skills_covered = count_evals()
    test_count = count_tests()
    script_count = len(list((sl.REPO_ROOT / "scripts").glob("*.py")))
    docs_count = len(list((sl.REPO_ROOT / "docs").glob("*.md")))

    lines = [
        START,
        "<!-- Generated by `python scripts/generate_readme_stats.py --write`. Do not hand-edit",
        "     this block — your changes will be overwritten. Edit skill frontmatter, scripts/,",
        "     tests/, docs/, or evals/ instead, then regenerate. -->",
        "",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Skills | **{total}** ({fmt_counter(type_counts, ['workflow', 'reference'])}) |",
        f"| Domains | {len(domain_counts)} — {fmt_counter(domain_counts, DOMAIN_ORDER)} |",
        f"| Level | {fmt_counter(level_counts, ['beginner', 'intermediate', 'advanced'])} |",
        f"| Risk level | {fmt_counter(risk_counts, ['low', 'medium', 'high', 'critical'])} |",
        f"| Evidence level | {fmt_counter(evidence_counts, ['primary', 'official-documentation', 'established-practice', 'heuristic', 'opinion'])} |",
        f"| Eval cases | {eval_files} case file(s) covering {eval_skills_covered}/{total} skills — structural sanity only, not automated grading (see `evals/SCHEMA.md`) |",
        f"| Unit tests | {test_count} (stdlib `unittest`, no extra dependencies) |",
        f"| Scripts / docs | {script_count} scripts in `scripts/`, {docs_count} policy docs in `docs/` |",
        END,
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print(f"README.md is missing {START} / {END} markers")
        return 1

    pre, rest = text.split(START, 1)
    _, post = rest.split(END, 1)
    new_block = render()
    new_text = pre + new_block + post

    if args.write:
        README.write_text(new_text, encoding="utf-8")
        print("README.md PROJECT-STATS block updated")
        return 0

    if new_text != text:
        print("README.md PROJECT-STATS block is stale — run `python scripts/generate_readme_stats.py --write`")
        return 1
    print("README.md PROJECT-STATS block is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
